// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// Support both naming conventions to match render.yaml (VITE_SUPABASE_ANON_KEY) and .env.example (VITE_SUPABASE_PUBLISHABLE_KEY)
const SUPABASE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

const hasValidSupabaseConfig = Boolean(SUPABASE_URL && SUPABASE_KEY);

// Set to "true" only when you explicitly want background refresh calls.
// Keeping it disabled by default avoids noisy retry loops when DNS/network is unstable.
const shouldAutoRefresh = import.meta.env.VITE_SUPABASE_AUTO_REFRESH === 'true';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

if (!hasValidSupabaseConfig) {
  console.error('Supabase environment variables are missing!');
  console.error('VITE_SUPABASE_URL:', SUPABASE_URL);
  console.error('VITE_SUPABASE_ANON_KEY:', import.meta.env.VITE_SUPABASE_ANON_KEY);
  console.error('VITE_SUPABASE_PUBLISHABLE_KEY:', import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);
  console.error('Please create a .env file with VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY');
}

export const isSupabaseConfigured = hasValidSupabaseConfig;

// Create client even with missing vars to avoid breaking the app.
// Calls are guarded in auth helpers so the UI can degrade gracefully.
export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_KEY || 'placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: hasValidSupabaseConfig,
      autoRefreshToken: hasValidSupabaseConfig && shouldAutoRefresh,
    }
  }
);
